const data = {
  products: [
    {
      name: 'Black shirt',
      slug: 'black-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStocks: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStocks: 20,
      description: 'Smart looking pants',
    },

    {
      name: 'Fit pants',
      slug: 'fit-shirt',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStocks: 20,
      description: 'A popular pair of pants',
    },
    {
      name: 'Classic pants',
      slug: 'classic-shirt',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStocks: 20,
      description: 'A popular pair of pants',
    },
  ],
};

export default data;
